# Generated by Django 2.2.6 on 2019-10-07 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=30)),
                ('product_model', models.CharField(max_length=30)),
                ('product_slug', models.SlugField(blank=True, max_length=450, null=True)),
                ('product_title', models.CharField(max_length=150)),
                ('product_brand', models.CharField(max_length=150)),
                ('product_add_date', models.DateTimeField(auto_now_add=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product_categories')),
            ],
            options={
                'unique_together': {('product_id', 'product_model')},
            },
        ),
        migrations.CreateModel(
            name='seller_details',
            fields=[
                ('seller_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('FName', models.CharField(max_length=30)),
                ('LName', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=30)),
                ('Mobile', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='product_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image1', models.FileField(upload_to='product/gallery/')),
                ('product_image2', models.FileField(upload_to='product/gallery/')),
                ('product_image3', models.FileField(upload_to='product/gallery/')),
                ('product_image4', models.FileField(upload_to='product/gallery/')),
                ('product_image5', models.FileField(upload_to='product/gallery/')),
                ('product_image6', models.FileField(upload_to='product/gallery/')),
                ('product_image7', models.FileField(upload_to='product/gallery/')),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product_table')),
            ],
        ),
        migrations.CreateModel(
            name='sellers_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.CharField(max_length=10)),
                ('product_discount', models.CharField(blank=True, default='', max_length=3)),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product_table')),
                ('seller_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.seller_details')),
            ],
            options={
                'unique_together': {('product_model', 'seller_name')},
            },
        ),
    ]
