# Generated by Django 2.2.6 on 2019-10-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellers_product',
            name='product_discount_price',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
