# Generated by Django 3.0.1 on 2020-03-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_sellers_product_product_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='product_image2',
            field=models.FileField(blank=True, null=True, upload_to='product/gallery/'),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='product_image3',
            field=models.FileField(blank=True, null=True, upload_to='product/gallery/'),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='product_image4',
            field=models.FileField(blank=True, null=True, upload_to='product/gallery/'),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='product_image5',
            field=models.FileField(blank=True, null=True, upload_to='product/gallery/'),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='product_image6',
            field=models.FileField(blank=True, null=True, upload_to='product/gallery/'),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='product_image7',
            field=models.FileField(blank=True, null=True, upload_to='product/gallery/'),
        ),
    ]
