# Generated by Django 2.2.6 on 2019-10-17 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_sellers_product_product_discount_price'),
        ('vs24', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product_table')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.sellers_product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vs24.Registration')),
            ],
            options={
                'unique_together': {('product_id', 'seller')},
            },
        ),
    ]
