# Generated by Django 3.0.1 on 2020-03-29 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vs24', '0001_initial'),
        ('product', '0003_auto_20200328_1649'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart_table',
            unique_together={('product_id', 'seller', 'user')},
        ),
    ]
