# Generated by Django 3.0.1 on 2020-04-07 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vs24', '0001_initial'),
        ('product', '0003_auto_20200328_1649'),
        ('cart', '0002_auto_20200329_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=30)),
                ('product_id', models.CharField(max_length=50)),
                ('process', models.CharField(default='Pending', max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('current_date', models.DateField(blank=True)),
                ('current_time', models.TimeField(blank=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.sellers_product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vs24.Registration')),
            ],
        ),
    ]
