# Generated by Django 3.0.1 on 2020-04-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_checkout_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout_order',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='checkout_order',
            name='land_mark',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='checkout_order',
            name='mobile',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='checkout_order',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='checkout_order',
            name='pincode',
            field=models.CharField(default='', max_length=20),
        ),
    ]
