# Generated by Django 3.0.1 on 2020-04-07 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200328_1649'),
        ('cart', '0004_auto_20200407_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout_order',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.seller_details'),
        ),
    ]
