# Generated by Django 2.2.6 on 2020-04-12 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20200407_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout_order',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product_table'),
        ),
    ]
