# Generated by Django 2.2.6 on 2020-04-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20200412_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout_order',
            name='process',
            field=models.CharField(default='Failed', max_length=30),
        ),
    ]
