# Generated by Django 2.1.7 on 2019-06-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('FName', models.CharField(max_length=30)),
                ('LName', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=30)),
                ('Mobile', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
    ]
