# Generated by Django 2.1.7 on 2019-06-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vs24', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Email',
            field=models.EmailField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='LName',
            field=models.CharField(max_length=30),
        ),
    ]
